### ISSUE TITLE
3455 instead of 3392 clusters in cluster_arrival.py

### ISSUE THREAD

**Issue by NZubia** [adbrebs/taxi#11]
Hi

First of all, I want to say thank you for all your work and for sharing it to us.

I have one question, I have done all the instructions you wrote, but when I run the cluster_arrival.py the result of the code is 3455 clusters instead of 3392 of your document. Did you do any preparation of the data before run it that script?

Thank you for your attention. And sorry for my English, it is a little bad

Regards

**Comment by hma02** [comment]
@NZubia 
I have the same problem. Have you figured out the reason?
maybe the scipy.cluster MeanShift algorithm is updated? 
or bw=0.0200442488592 overwritten by bw = 0.001 caused this problem?

**Comment by mshahabi** [comment]
@NZubia I am wondering how long it took for you to run the make_tvt.py code in order to generate valid.hdf5 files.. mine is like taking for ever... just o not know why

**Comment by NZubia** [comment]
@hma02 
I never could figure it why the number of clusters is different, but I think you are right and the value of bw is the cause of that.

**Comment by NZubia** [comment]
@mshahabi I dont remember how long it tooks exactly but I think the algorithm dont spent more than an one hour to generate the file. Is the training algorithm the one that spent more than a two day to run.

**Comment by Octobeeeer** [comment]
thanks for your work
