### ISSUE TITLE
undefined symbol: _ZdlPvm'

### ISSUE THREAD

**Issue by 1729564921** [adbrebs/taxi#14]
Thank you for sharing your work!

When I run the train.py, This error will appear.

ImportError: ('The following error happened while compiling the node', DeepCopyOp(TensorConstant{0.0}), '\n', '/home/lab508/.theano/compiledir_Linux-4.10--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64/tmpaxNtgT/407a281f6283a0ff044720a43f4d2c3f.so: undefined symbol: _ZdlPvm', '[DeepCopyOp(TensorConstant{0.0})]')

**Comment by Alexis211** [comment]
This is a Theano issue. Check your Theano install (especially the BLAS libraries, I think it uses libatlas but not sure).
