### ISSUE TITLE
FilterSources error

### ISSUE THREAD

**Issue by eighteight** [adbrebs/taxi#9]
$eight: taxi: ./prepare.sh 
This script will prepare the data.
You should run it from inside the repository.
You should set the TAXI_PATH variable to where the data downloaded from kaggle is.
Three data files are needed: train.csv.zip, test.csv.zip and metaData_taxistandsID_name_GPSlocation.csv.zip. They can be found at the following url: https://www.kaggle.com/c/pkdd-15-predict-taxi-service-trajectory-i/data

# Checking dependencies
h5py... version 2.5.0 (we used version 2.5.0)
theano... version 0.7.0 (we used version 0.7.0.dev)
fuel... version 0.0.1 (we used version 0.0.1)
blocks... version 0.0.1 (we used version 0.0.1)
sklearn... version 0.16.1 (we used version 0.16.1)

# Checking data
TAXI_PATH is set to kaggle-data
md5sum train.csv.zip... 87a1b75adfde321dc163160b495964e8 ok
md5sum test.csv.zip... 47133bf7349cb80cc668fa56af8ce743 ok
md5sum metaData_taxistandsID_name_GPSlocation.csv.zip... fecec7286191af868ce8fb208f5c7643 ok

# Extracting data
unziping train.csv.zip... Archive:  kaggle-data/train.csv.zip
  inflating: kaggle-data/train.csv   
ok
md5sum train.csv... 68cc499ac4937a3079ebf69e69e73971 ok
unziping test.csv.zip... Archive:  kaggle-data/test.csv.zip
  inflating: kaggle-data/test.csv    
ok
md5sum test.csv... f2ceffde9d98e3c49046c7d998308e71 ok
unziping metaData_taxistandsID_name_GPSlocation.csv.zip... Archive:  kaggle-data/metaData_taxistandsID_name_GPSlocation.csv.zip
  inflating: kaggle-data/metaData_taxistandsID_name_GPSlocation.csv  
  inflating: kaggle-data/__MACOSX/._metaData_taxistandsID_name_GPSlocation.csv  
ok
patching error in metadata csv... ok
md5sum metaData_taxistandsID_name_GPSlocation.csv... 724805b0b1385eb3efc02e8bdfe9c1df ok

# Conversion of training set to HDF5
This might take some time
read train: begin
read train: 10000 done
......
read train: 1710000 done
read train: writing
read train: end
First origin_call not present in training set:  57106
read test: begin
read test: writing
read test: end

# Generation of validation set
This might take some time
initialization... ok
cutting... Number of cuts: 5
Traceback (most recent call last):
  File "data/make_valid_cut.py", line 78, in <module>
    make_valid(sys.argv[1], outpath)
  File "data/make_valid_cut.py", line 24, in make_valid
    for line in taxi_it('train'):
  File "/Users/eight/repos/taxi/data/hdf5.py", line 63, in taxi_it
    dataset = TaxiDataset(which_set, filename)
  File "/Users/eight/repos/taxi/data/hdf5.py", line 16, in __init__
    super(TaxiDataset, self).__init__(self.data_path, (which_set,), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fuel/datasets/hdf5.py", line 146, in __init__
    "{}.".format(self.available_splits))
ValueError: '('train',)' split is not provided by this dataset. Available splits are (u'test', u'unique_taxi_id', u'train', u'stands', u'unique_origin_call').
ok

# Generation of destination cluster
This might take some time
generating... Traceback (most recent call last):
  File "data_analysis/cluster_arrival.py", line 13, in <module>
    from data.transformers import add_destination
  File "/Users/eight/repos/taxi/data/transformers.py", line 9, in <module>
    from fuel.transformers import Batch, Mapping, SortMapping, Transformer, Unpack, FilterSources
ImportError: cannot import name FilterSources
ok

# Creating output folders
mkdir model_data... mkdir: model_data: File exists
ok
mkdir output... mkdir: output: File exists
ok

The data was successfully prepared
To train the winning model on gpu, you can now run the following command:
THEANO_FLAGS=floatX=float32,device=gpu,optimizer=fast_run python2 train.py dest_mlp_tgtcls_1_cswdtx_alexandre

$eight: taxi: THEANO_FLAGS=floatX=float32,device=gpu,optimizer=fast_run python2 train.py dest_mlp_tgtcls_1_cswdtx_alexandre
Using gpu device 0: GeForce GT 650M
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    config = importlib.import_module('.%s' % model_name, 'config')
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/eight/repos/taxi/config/dest_mlp_tgtcls_1_cswdtx_alexandre.py", line 8, in <module>
    from model.dest_mlp_tgtcls import Model, Stream
  File "/Users/eight/repos/taxi/model/dest_mlp_tgtcls.py", line 7, in <module>
    from model.mlp import FFMLP, Stream
  File "/Users/eight/repos/taxi/model/mlp.py", line 13, in <module>
    from data import transformers
  File "/Users/eight/repos/taxi/data/transformers.py", line 9, in <module>
    from fuel.transformers import Batch, Mapping, SortMapping, Transformer, Unpack, FilterSources
**ImportError: cannot import name FilterSources**
$eight: taxi:

**Comment by ejls** [comment]
Hi,
Thanks for the report, this seems to be an API change, we'll try to fix this, but Fuel is kind of experimental and quickly evolving, even after updating our code, you will run into others issues like https://github.com/mila-udem/fuel/issues/201, we would recommend downgrading to a previous version.
We can guarantee that our code works with the following commit of blocks and fuel:
https://github.com/mila-udem/fuel/commit/ed725a7ff9f3d080ef882d4ae7e4373c4984f35a
https://github.com/mila-udem/blocks/commit/1e0aca9171611be4df404129d91a991354e67730
For now we will update the README and you will have to check out the old versions by hand, I'll try to hack a script to make this easier later this week.

**Comment by eighteight** [comment]
Closing: it seems to be working with these commits.
